; PlatformIO Project Configuration File

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

board_build.f_cpu = 240000000L
board_build.flash_mode = qio

build_flags =
    -Wl,-u,_printf_float
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0
    -I src/config
    -I src/hardware
    -I src/sensors
    -I src/control
    -I src/communication
    -I src/utils
    -I src/tasks

upload_speed = 921600
monitor_speed = 921600
monitor_filters = esp32_exception_decoder
monitor_rts = 0
monitor_dtr = 0